package globalerrors

import "google.golang.org/grpc/codes"

var grpcStatusCodesMap = map[error]codes.Code{
	BadRequest:                    codes.InvalidArgument,
	Unauthorized:                  codes.Unauthenticated,
	PaymentRequired:               codes.PermissionDenied,
	Forbidden:                     codes.PermissionDenied,
	NotFound:                      codes.NotFound,
	MethodNotAllowed:              codes.Unimplemented,
	NotAcceptable:                 codes.FailedPrecondition,
	ProxyAuthRequired:             codes.Unauthenticated,
	RequestTimeout:                codes.DeadlineExceeded,
	Conflict:                      codes.Aborted,
	Gone:                          codes.NotFound,
	LengthRequired:                codes.InvalidArgument,
	PreconditionFailed:            codes.FailedPrecondition,
	RequestEntityTooLarge:         codes.ResourceExhausted,
	RequestURITooLong:             codes.InvalidArgument,
	UnsupportedMediaType:          codes.InvalidArgument,
	RequestedRangeNotSatisfiable:  codes.OutOfRange,
	ExpectationFailed:             codes.FailedPrecondition,
	Teapot:                        codes.Unknown,
	MisdirectedRequest:            codes.FailedPrecondition,
	UnprocessableEntity:           codes.InvalidArgument,
	Locked:                        codes.FailedPrecondition,
	FailedDependency:              codes.FailedPrecondition,
	TooEarly:                      codes.FailedPrecondition,
	UpgradeRequired:               codes.Unimplemented,
	PreconditionRequired:          codes.FailedPrecondition,
	TooManyRequests:               codes.ResourceExhausted,
	RequestHeaderFieldsTooLarge:   codes.InvalidArgument,
	UnavailableForLegalReasons:    codes.PermissionDenied,
	InternalServerError:           codes.Internal,
	NotImplemented:                codes.Unimplemented,
	BadGateway:                    codes.Internal,
	ServiceUnavailable:            codes.Unavailable,
	GatewayTimeout:                codes.DeadlineExceeded,
	HTTPVersionNotSupported:       codes.Unimplemented,
	VariantAlsoNegotiates:         codes.Internal,
	InsufficientStorage:           codes.ResourceExhausted,
	LoopDetected:                  codes.Aborted,
	NotExtended:                   codes.Internal,
	NetworkAuthenticationRequired: codes.Unauthenticated,
}
